function opt(value, text) {
  return { value, text };
}

const CLAIM_STATUS_OPTIONS = [
  opt('new', 'New'),
  opt('open_investigation', 'Open - Investigation'),
  opt('open_documents', 'Open - Awaiting Documents'),
  opt('open_insurance', 'Open - Insurance Review'),
  opt('open_negotiation', 'Open - Negotiation'),
  opt('litigation', 'Litigation'),
  opt('settled', 'Settled'),
  opt('closed_no_payment', 'Closed - No Payment'),
  opt('closed_paid', 'Closed - Paid'),
];

const CLAIM_TYPE_OPTIONS = [
  opt('auto_accident', 'Auto Accident'),
  opt('cargo_damage', 'Cargo Damage'),
  opt('cargo_shortage', 'Cargo Shortage / Loss'),
  opt('cargo_contamination', 'Cargo Contamination'),
  opt('property_damage', 'Property Damage'),
  opt('bodily_injury', 'Bodily Injury'),
  opt('trailer_damage', 'Trailer Damage'),
  opt('equipment_damage', 'Equipment Damage'),
  opt('theft', 'Theft'),
  opt('fire', 'Fire'),
  opt('environmental', 'Environmental / Spill'),
  opt('other', 'Other'),
];

const EMPLOYMENT_OPTIONS = [
  opt('employee', 'Employee'),
  opt('owner_operator', 'Owner-Operator'),
  opt('independent_contractor', 'Independent Contractor'),
  opt('other', 'Other'),
];

const YES_NO = [opt('yes', 'Yes'), opt('no', 'No')];
const YES_NO_PARTIAL = [opt('yes', 'Yes'), opt('no', 'No'), opt('partially', 'Partially')];
const YES_NO_NA = [opt('yes', 'Yes'), opt('no', 'No'), opt('na', 'Not Applicable')];
const YES_NO_NA_SHORT = [opt('yes', 'Yes'), opt('no', 'No'), opt('na', 'N/A')];
const YES_NO_PENDING = [opt('yes', 'Yes'), opt('no', 'No'), opt('pending', 'Pending')];
const YES_NO_UNKNOWN = [opt('yes', 'Yes'), opt('no', 'No'), opt('unknown', 'Unknown')];
const YES_NO_POSSIBLE = [opt('yes', 'Yes'), opt('no', 'No'), opt('possible', 'Possible')];

const INJURY_ROLE_OPTIONS = [
  opt('driver', 'Driver'),
  opt('passenger', 'Passenger'),
  opt('other_driver', 'Other Driver'),
  opt('customer_public', 'Customer / Public'),
  opt('employee', 'Employee'),
  opt('other', 'Other'),
];

const LIABILITY_OPTIONS = [
  opt('none', 'None / Minimal'),
  opt('low', 'Low'),
  opt('moderate', 'Moderate'),
  opt('high', 'High'),
  opt('unknown', 'Unknown'),
];

const MANAGEMENT_OPTIONS = [
  opt('no_action', 'No Action Required'),
  opt('follow_up', 'Follow-Up Required'),
  opt('insurance_follow_up', 'Insurance Follow-Up Required'),
  opt('customer_follow_up', 'Customer Follow-Up Required'),
  opt('attorney_follow_up', 'Attorney Follow-Up Required'),
  opt('driver_follow_up', 'Driver Follow-Up Required'),
  opt('documentation', 'Documentation Required'),
  opt('settlement_discussion', 'Settlement Discussion Required'),
  opt('escalation', 'Escalation Required'),
];

const RESOLUTION_OPTIONS = [
  opt('paid_insurance', 'Paid by Insurance'),
  opt('paid_company', 'Paid by Company'),
  opt('settled', 'Settled'),
  opt('denied', 'Denied'),
  opt('withdrawn', 'Withdrawn'),
  opt('no_liability', 'No Liability'),
  opt('other', 'Other'),
];

const DOCUMENT_OPTIONS = [
  opt('drivers_statement', "Driver's Statement"),
  opt('drivers_license', "Driver's License"),
  opt('employment_info', "Driver's Employment / Contractor Information"),
  opt('vehicle_registration', 'Vehicle Registration'),
  opt('insurance_certificate', 'Insurance Certificate'),
  opt('police_report', 'Police Report'),
  opt('accident_report', 'Accident Report'),
  opt('photos_vehicle', 'Photos - Vehicle'),
  opt('photos_scene', 'Photos - Scene'),
  opt('photos_cargo', 'Photos - Cargo'),
  opt('dashcam', 'Dashcam / Camera Footage'),
  opt('gps_eld', 'GPS / ELD Records'),
  opt('bol', 'BOL'),
  opt('pod', 'POD'),
  opt('rate_confirmation', 'Rate Confirmation'),
  opt('freight_invoice', 'Freight Invoice'),
  opt('cargo_invoice', 'Cargo Invoice / Purchase Documents'),
  opt('inspection_report', 'Inspection Report'),
  opt('repair_estimate', 'Repair Estimate'),
  opt('repair_invoice', 'Repair Invoice'),
  opt('salvage_docs', 'Salvage Documentation'),
  opt('medical_docs', 'Medical Documentation'),
  opt('attorney_correspondence', 'Attorney Correspondence'),
  opt('customer_correspondence', 'Customer Correspondence'),
  opt('insurance_correspondence', 'Insurance Correspondence'),
  opt('claim_form_doc', 'Claim Form'),
  opt('settlement_agreement', 'Settlement Agreement'),
  opt('release_doc', 'Release'),
  opt('proof_of_payment', 'Proof of Payment'),
];

const CLOSURE_REQUIREMENT_OPTIONS = [
  opt('liability_documented', 'Liability / coverage determination is documented'),
  opt('evidence_collected', 'All relevant evidence is collected'),
  opt('invoices_received', 'All invoices and supporting documents are received'),
  opt('insurance_resolved', 'Insurance claim is resolved'),
  opt('payments_completed', 'Outstanding payments are completed'),
  opt('settlement_release', 'Settlement / release is obtained when applicable'),
  opt('final_financial', 'Final financial amount is recorded'),
  opt('correspondence_saved', 'All correspondence is saved'),
  opt('management_reviewed', 'Management has reviewed the claim'),
  opt('marked_closed', 'Claim is marked CLOSED'),
];

/** Single-select groups stay exclusive on the posted message. Multi groups do not. */
const GROUPS = [
  {
    key: 'claimStatus',
    label: '1. Claim Status',
    multi: false,
    modal: 'radio',
    initial: 'new',
    options: CLAIM_STATUS_OPTIONS,
  },
  {
    key: 'claimType',
    label: '1. Type of Claim',
    multi: false,
    modal: 'select',
    placeholder: 'Select claim type',
    options: CLAIM_TYPE_OPTIONS,
  },
  {
    key: 'employmentType',
    label: '3. Employee / Contractor',
    multi: false,
    modal: 'radio',
    options: EMPLOYMENT_OPTIONS,
  },
  {
    key: 'loadDelivered',
    label: '4. Was the load delivered?',
    multi: false,
    modal: 'radio',
    options: YES_NO_PARTIAL,
  },
  {
    key: 'policeCalled',
    label: '5. Police / Highway Patrol called?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'emsCalled',
    label: '5. EMS / Fire Department called?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'anyoneInjured',
    label: '8. Was anyone injured?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'injuryRole',
    label: '8. Relationship / Role',
    multi: false,
    modal: 'radio',
    options: INJURY_ROLE_OPTIONS,
  },
  {
    key: 'attorneyInvolved',
    label: '8. Attorney Involved?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'documents',
    label: '9. Document Checklist',
    multi: true,
    modal: 'checkboxes',
    hint: 'Check each document received. This list stays multi-select on the post.',
    options: DOCUMENT_OPTIONS,
  },
  {
    key: 'coverageConfirmed',
    label: '10. Coverage Confirmed?',
    multi: false,
    modal: 'radio',
    options: YES_NO_PENDING,
  },
  {
    key: 'subrogationPotential',
    label: '10. Subrogation Potential',
    multi: false,
    modal: 'radio',
    options: YES_NO_UNKNOWN,
  },
  {
    key: 'potentialLiability',
    label: '14. Potential Liability',
    multi: false,
    modal: 'radio',
    options: LIABILITY_OPTIONS,
  },
  {
    key: 'legalActionExpected',
    label: '14. Legal Action Expected?',
    multi: false,
    modal: 'radio',
    options: YES_NO_POSSIBLE,
  },
  {
    key: 'managementStatus',
    label: '16. Management Status',
    multi: false,
    modal: 'radio',
    options: MANAGEMENT_OPTIONS,
  },
  {
    key: 'resolution',
    label: '17. Claim Resolution',
    multi: false,
    modal: 'radio',
    options: RESOLUTION_OPTIONS,
  },
  {
    key: 'releaseObtained',
    label: '17. Settlement / Release Obtained?',
    multi: false,
    modal: 'radio',
    options: YES_NO_NA,
  },
  {
    key: 'subrogationRecovered',
    label: '17. Subrogation Recovered?',
    multi: false,
    modal: 'radio',
    options: YES_NO_NA,
  },
  {
    key: 'docsReceived',
    label: '18. All Required Documents Received?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'paymentsCompleted',
    label: '18. All Payments Completed?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'releaseFiled',
    label: '18. Final Release / Settlement Filed?',
    multi: false,
    modal: 'radio',
    options: YES_NO_NA_SHORT,
  },
  {
    key: 'fileComplete',
    label: '18. Claim File Complete?',
    multi: false,
    modal: 'radio',
    options: YES_NO,
  },
  {
    key: 'closureRequirements',
    label: 'Claim file is not closed until',
    multi: true,
    modal: 'checkboxes',
    hint: 'Check every item that is done. This list stays multi-select on the post.',
    options: CLOSURE_REQUIREMENT_OPTIONS,
  },
];

function text(key, label, section, extra = {}) {
  return { key, label, section, type: 'text', ...extra };
}

const TEXT_FIELDS = [
  text('claimNumber', 'Claim Number', '1. Claim information', { required: true }),
  text('dateClaimReported', 'Date Claim Reported', '1. Claim information', { type: 'date' }),
  text('dateOfLoss', 'Date of Loss / Incident', '1. Claim information', { type: 'date' }),
  text('timeOfLoss', 'Time of Loss / Incident', '1. Claim information', { type: 'time' }),
  text('claimTypeOther', 'Type of Claim - Other', '1. Claim information'),
  text('dateClaimOpened', 'Date Claim Opened', '1. Claim information', { type: 'date' }),
  text('assignedEmployee', 'Assigned Employee / Claim Coordinator', '1. Claim information'),

  text('companyName', 'Company Name', '2. Trucking company'),
  text('dotNumber', 'DOT Number', '2. Trucking company'),
  text('mcNumber', 'MC Number', '2. Trucking company'),
  text('companyContact', 'Company Contact', '2. Trucking company'),
  text('companyPhone', 'Phone', '2. Trucking company'),
  text('companyEmail', 'Email', '2. Trucking company'),
  text('insuranceCompany', 'Insurance Company', '2. Trucking company'),
  text('insurancePolicyNumber', 'Insurance Policy Number', '2. Trucking company'),
  text('insuranceAdjuster', 'Insurance Adjuster', '2. Trucking company'),
  text('adjusterPhone', 'Adjuster Phone', '2. Trucking company'),
  text('adjusterEmail', 'Adjuster Email', '2. Trucking company'),

  text('driverName', 'Driver Name', '3. Driver / vehicle'),
  text('driverPhone', 'Driver Phone', '3. Driver / vehicle'),
  text('employmentTypeOther', 'Employee / Contractor - Other', '3. Driver / vehicle'),
  text('truckNumber', 'Truck Number', '3. Driver / vehicle'),
  text('unitVin', 'Unit / VIN', '3. Driver / vehicle'),
  text('licensePlate', 'License Plate', '3. Driver / vehicle'),
  text('trailerNumber', 'Trailer Number', '3. Driver / vehicle'),
  text('trailerVin', 'Trailer VIN', '3. Driver / vehicle'),
  text('trailerLicensePlate', 'Trailer License Plate', '3. Driver / vehicle'),
  text('carrierOwner', 'Carrier / Owner of Equipment', '3. Driver / vehicle'),

  text('shipper', 'Shipper', '4. Load / cargo'),
  text('consignee', 'Consignee', '4. Load / cargo'),
  text('broker', 'Broker', '4. Load / cargo'),
  text('loadNumber', 'Load / Shipment Number', '4. Load / cargo'),
  text('bolNumber', 'BOL Number', '4. Load / cargo'),
  text('poNumber', 'PO Number', '4. Load / cargo'),
  text('commodity', 'Commodity', '4. Load / cargo'),
  text('quantity', 'Quantity', '4. Load / cargo'),
  text('cargoValue', 'Cargo Value', '4. Load / cargo', { money: true }),
  text('freightCharges', 'Freight Charges', '4. Load / cargo', { money: true }),
  text('pickupDate', 'Pickup Date', '4. Load / cargo', { type: 'date' }),
  text('pickupLocation', 'Pickup Location', '4. Load / cargo'),
  text('deliveryDate', 'Delivery Date', '4. Load / cargo', { type: 'date' }),
  text('deliveryLocation', 'Delivery Location', '4. Load / cargo'),
  text('deliveryException', 'Delivery Status / Exception', '4. Load / cargo', { type: 'multiline' }),

  text('incidentLocation', 'Location of Incident / Loss', '5. Incident / loss', { type: 'multiline' }),
  text('cityState', 'City / State', '5. Incident / loss'),
  text('weather', 'Weather Conditions', '5. Incident / loss'),
  text('roadConditions', 'Road Conditions', '5. Incident / loss'),
  text('incidentDescription', 'Description of What Happened', '5. Incident / loss', { type: 'multiline' }),
  text('policeAgency', 'Police / Agency', '5. Incident / loss'),
  text('reportNumber', 'Report Number', '5. Incident / loss'),
  text('dateReportObtained', 'Date Report Obtained', '5. Incident / loss', { type: 'date' }),

  text('otherPartyName', 'Other Party Name', '6. Other parties'),
  text('otherPartyCompany', 'Other Party Company', '6. Other parties'),
  text('otherPartyPhone', 'Other Party Phone', '6. Other parties'),
  text('otherPartyEmail', 'Other Party Email', '6. Other parties'),
  text('otherPartyAddress', 'Other Party Address', '6. Other parties'),
  text('otherPartyInsurance', 'Other Party Insurance Company', '6. Other parties'),
  text('otherPartyPolicy', 'Other Party Policy Number', '6. Other parties'),
  text('otherPartyClaimNumber', 'Other Party Claim Number', '6. Other parties'),
  text('additionalPartyName', 'Additional Party Name / Company', '6. Other parties'),
  text('additionalPartyRole', 'Additional Party Role', '6. Other parties'),
  text('additionalPartyContact', 'Additional Party Contact', '6. Other parties'),
  text('additionalPartyInsurance', 'Additional Party Insurance', '6. Other parties'),

  text('damageDescription', 'Description of Damage or Loss', '7. Damage / loss', { type: 'multiline' }),
  text('estimatedDamage', 'Estimated Damage', '7. Damage / loss', { money: true }),
  text('actualDamage', 'Actual Damage', '7. Damage / loss', { money: true }),
  text('estimatedCargoValue', 'Estimated Cargo Value', '7. Damage / loss', { money: true }),
  text('amountClaimed', 'Amount Claimed', '7. Damage / loss', { money: true }),
  text('amountReserved', 'Amount Reserved by Insurance', '7. Damage / loss', { money: true }),
  text('deductible', 'Deductible', '7. Damage / loss', { money: true }),
  text('potentialExposure', 'Potential Company Exposure', '7. Damage / loss', { money: true }),
  text('salvageValue', 'Salvage Value', '7. Damage / loss', { money: true }),
  text('repairFacility', 'Repair Facility / Inspection Location', '7. Damage / loss'),
  text('repairContact', 'Repair Contact', '7. Damage / loss'),

  text('injuredPerson', 'Injured Person', '8. Injury'),
  text('injuryRoleOther', 'Relationship / Role - Other', '8. Injury'),
  text('injuryDescription', 'Description of Injury', '8. Injury', { type: 'multiline' }),
  text('treatment', 'Treatment Received', '8. Injury', { type: 'multiline' }),
  text('medicalFacility', 'Medical Facility', '8. Injury'),
  text('attorneyName', 'Attorney Name / Firm', '8. Injury'),
  text('attorneyContact', 'Attorney Phone / Email', '8. Injury'),
  text('documentsOther', 'Document Checklist - Other', '9. Documents'),

  text('insuranceClaimNumber', 'Insurance Claim Number', '10. Insurance claim'),
  text('dateReportedToInsurance', 'Date Claim Reported to Insurance', '10. Insurance claim', { type: 'date' }),
  text('coverageAdjusterName', 'Adjuster Name', '10. Insurance claim'),
  text('coverageAdjusterPhone', 'Adjuster Phone', '10. Insurance claim'),
  text('coverageAdjusterEmail', 'Adjuster Email', '10. Insurance claim'),
  text('dateInitialReserve', 'Date Initial Reserve Established', '10. Insurance claim', { type: 'date' }),
  text('currentReserve', 'Current Reserve', '10. Insurance claim', { money: true }),
  text('insuranceDeductible', 'Deductible', '10. Insurance claim', { money: true }),
  text('coverageIssues', 'Coverage Issues / Reservation of Rights', '10. Insurance claim', { type: 'multiline' }),
  text('subrogationParty', 'Subrogation Party', '10. Insurance claim'),

  text('activityLog', 'Claim Activity / Communication Log', '11. Activity log', {
    type: 'multiline',
    placeholder: 'Date | Contact | Method | Update | Follow-up | By whom | Due date',
  }),
  text('evidenceTracking', 'Document / Evidence Tracking', '12. Evidence tracking', {
    type: 'multiline',
    placeholder: 'Document | Requested | Received | From whom | Location | Notes',
  }),

  text('initialEstimatedExposure', 'Initial Estimated Exposure', '13. Financial tracking', { money: true }),
  text('currentEstimatedExposure', 'Current Estimated Exposure', '13. Financial tracking', { money: true }),
  text('insuranceReserve', 'Insurance Reserve', '13. Financial tracking', { money: true }),
  text('companyReserve', 'Company Reserve', '13. Financial tracking', { money: true }),
  text('financialDeductible', 'Deductible', '13. Financial tracking', { money: true }),
  text('paymentsMade', 'Payments Made', '13. Financial tracking', { money: true }),
  text('legalFees', 'Legal Fees', '13. Financial tracking', { money: true }),
  text('adjustingFees', 'Adjusting / Investigation Fees', '13. Financial tracking', { money: true }),
  text('repairCosts', 'Repair Costs', '13. Financial tracking', { money: true }),
  text('cargoReplacementCosts', 'Cargo Replacement Costs', '13. Financial tracking', { money: true }),
  text('otherExpenses', 'Other Expenses', '13. Financial tracking', { money: true }),
  text('totalPaidToDate', 'Total Paid to Date', '13. Financial tracking', { money: true }),
  text('outstandingAmount', 'Outstanding Amount', '13. Financial tracking', { money: true }),
  text('potentialFinalCost', 'Potential Final Cost', '13. Financial tracking', { money: true }),

  text('currentSummary', 'Current Claim Status / Summary', '14. Current assessment', { type: 'multiline' }),
  text('preventingClosure', 'What is currently preventing closure?', '14. Current assessment', { type: 'multiline' }),
  text('outstandingDocuments', 'Outstanding Documents', '14. Current assessment', { type: 'multiline' }),
  text('outstandingInformation', 'Outstanding Information', '14. Current assessment', { type: 'multiline' }),
  text('outstandingPayments', 'Outstanding Payments', '14. Current assessment', { type: 'multiline' }),
  text('currentEstimatedLiability', 'Current Estimated Liability', '14. Current assessment', { money: true }),

  text('nextActions', 'Next Action Items', '15. Next action items', {
    type: 'multiline',
    placeholder: 'Action | Responsible person | Date assigned | Due date | Completed date',
  }),

  text('lastReviewDate', 'Last Management Review Date', '16. Management review', { type: 'date' }),
  text('reviewedBy', 'Reviewed By', '16. Management review'),
  text('managementNotes', 'Management Notes', '16. Management review', { type: 'multiline' }),

  text('resolutionOther', 'Claim Resolution - Other', '17. Settlement / resolution'),
  text('settlementAmount', 'Settlement Amount', '17. Settlement / resolution', { money: true }),
  text('finalPaymentDate', 'Final Payment Date', '17. Settlement / resolution', { type: 'date' }),
  text('releaseDate', 'Release Date', '17. Settlement / resolution', { type: 'date' }),
  text('finalClaimCost', 'Final Claim Cost', '17. Settlement / resolution', { money: true }),
  text('insurancePaid', 'Insurance Paid', '17. Settlement / resolution', { money: true }),
  text('companyPaid', 'Company Paid', '17. Settlement / resolution', { money: true }),
  text('deductiblePaid', 'Deductible Paid', '17. Settlement / resolution', { money: true }),
  text('totalClaimCost', 'Total Claim Cost', '17. Settlement / resolution', { money: true }),
  text('subrogationRecovery', 'Subrogation Recovery', '17. Settlement / resolution', { money: true }),

  text('closureDate', 'Closure Date', '18. Claim closure', { type: 'date' }),
  text('closedBy', 'Closed By', '18. Claim closure'),
  text('finalClaimStatus', 'Final Claim Status', '18. Claim closure'),
  text('lessonsLearned', 'Lessons Learned / Preventive Action', '18. Claim closure', { type: 'multiline' }),
  text('additionalNotes', 'Additional Notes', '18. Claim closure', { type: 'multiline' }),
  text('formDate', 'Date', '18. Claim closure', { type: 'date' }),
];

const TEXT_BY_KEY = Object.fromEntries(TEXT_FIELDS.map((field) => [field.key, field]));
const GROUP_BY_KEY = Object.fromEntries(GROUPS.map((group) => [group.key, group]));

const CLAIMS_STEPS = [
  {
    callbackId: 'claims_submit_1',
    title: 'Claim form (1/3)',
    submit: 'Next',
    intro:
      'Complete this form for every claim from the time it is reported until it is fully resolved and closed.',
    items: [
      { header: '1. CLAIM INFORMATION' },
      { text: 'claimNumber' },
      { text: 'dateClaimReported' },
      { text: 'dateOfLoss' },
      { text: 'timeOfLoss' },
      { group: 'claimStatus' },
      { group: 'claimType' },
      { text: 'claimTypeOther' },
      { text: 'dateClaimOpened' },
      { text: 'assignedEmployee' },
      { header: '2. TRUCKING COMPANY INFORMATION' },
      { text: 'companyName' },
      { text: 'dotNumber' },
      { text: 'mcNumber' },
      { text: 'companyContact' },
      { text: 'companyPhone' },
      { text: 'companyEmail' },
      { text: 'insuranceCompany' },
      { text: 'insurancePolicyNumber' },
      { text: 'insuranceAdjuster' },
      { text: 'adjusterPhone' },
      { text: 'adjusterEmail' },
      { header: '3. DRIVER / VEHICLE INFORMATION' },
      { text: 'driverName' },
      { text: 'driverPhone' },
      { group: 'employmentType' },
      { text: 'employmentTypeOther' },
      { text: 'truckNumber' },
      { text: 'unitVin' },
      { text: 'licensePlate' },
      { text: 'trailerNumber' },
      { text: 'trailerVin' },
      { text: 'trailerLicensePlate' },
      { text: 'carrierOwner' },
      { header: '4. LOAD / CARGO INFORMATION' },
      { text: 'shipper' },
      { text: 'consignee' },
      { text: 'broker' },
      { text: 'loadNumber' },
      { text: 'bolNumber' },
      { text: 'poNumber' },
      { text: 'commodity' },
      { text: 'quantity' },
      { text: 'cargoValue' },
      { text: 'freightCharges' },
      { text: 'pickupDate' },
      { text: 'pickupLocation' },
      { text: 'deliveryDate' },
      { text: 'deliveryLocation' },
      { group: 'loadDelivered' },
      { text: 'deliveryException' },
    ],
  },
  {
    callbackId: 'claims_submit_2',
    title: 'Claim form (2/3)',
    submit: 'Next',
    items: [
      { header: '5. INCIDENT / LOSS INFORMATION' },
      { text: 'incidentLocation' },
      { text: 'cityState' },
      { text: 'weather' },
      { text: 'roadConditions' },
      { text: 'incidentDescription' },
      { group: 'policeCalled' },
      { text: 'policeAgency' },
      { text: 'reportNumber' },
      { text: 'dateReportObtained' },
      { group: 'emsCalled' },
      { header: '6. OTHER PARTIES INVOLVED' },
      { text: 'otherPartyName' },
      { text: 'otherPartyCompany' },
      { text: 'otherPartyPhone' },
      { text: 'otherPartyEmail' },
      { text: 'otherPartyAddress' },
      { text: 'otherPartyInsurance' },
      { text: 'otherPartyPolicy' },
      { text: 'otherPartyClaimNumber' },
      { text: 'additionalPartyName' },
      { text: 'additionalPartyRole' },
      { text: 'additionalPartyContact' },
      { text: 'additionalPartyInsurance' },
      { header: '7. DAMAGE / LOSS INFORMATION' },
      { text: 'damageDescription' },
      { text: 'estimatedDamage' },
      { text: 'actualDamage' },
      { text: 'estimatedCargoValue' },
      { text: 'amountClaimed' },
      { text: 'amountReserved' },
      { text: 'deductible' },
      { text: 'potentialExposure' },
      { text: 'salvageValue' },
      { text: 'repairFacility' },
      { text: 'repairContact' },
      { header: '8. INJURY INFORMATION' },
      { group: 'anyoneInjured' },
      { text: 'injuredPerson' },
      { group: 'injuryRole' },
      { text: 'injuryRoleOther' },
      { text: 'injuryDescription' },
      { text: 'treatment' },
      { text: 'medicalFacility' },
      { group: 'attorneyInvolved' },
      { text: 'attorneyName' },
      { text: 'attorneyContact' },
      { header: '9. DOCUMENT CHECKLIST' },
      { group: 'documents' },
      { text: 'documentsOther' },
    ],
  },
  {
    callbackId: 'claims_submit_3',
    title: 'Claim form (3/3)',
    submit: 'Submit',
    items: [
      { header: '10. INSURANCE CLAIM INFORMATION' },
      { text: 'insuranceClaimNumber' },
      { text: 'dateReportedToInsurance' },
      { text: 'coverageAdjusterName' },
      { text: 'coverageAdjusterPhone' },
      { text: 'coverageAdjusterEmail' },
      { text: 'dateInitialReserve' },
      { text: 'currentReserve' },
      { text: 'insuranceDeductible' },
      { group: 'coverageConfirmed' },
      { text: 'coverageIssues' },
      { group: 'subrogationPotential' },
      { text: 'subrogationParty' },
      { header: '11. CLAIM ACTIVITY / COMMUNICATION LOG' },
      { text: 'activityLog' },
      { header: '12. DOCUMENT / EVIDENCE TRACKING' },
      { text: 'evidenceTracking' },
      { header: '13. FINANCIAL TRACKING' },
      { text: 'initialEstimatedExposure' },
      { text: 'currentEstimatedExposure' },
      { text: 'insuranceReserve' },
      { text: 'companyReserve' },
      { text: 'financialDeductible' },
      { text: 'paymentsMade' },
      { text: 'legalFees' },
      { text: 'adjustingFees' },
      { text: 'repairCosts' },
      { text: 'cargoReplacementCosts' },
      { text: 'otherExpenses' },
      { text: 'totalPaidToDate' },
      { text: 'outstandingAmount' },
      { text: 'potentialFinalCost' },
      { header: '14. CURRENT CLAIM ASSESSMENT' },
      { text: 'currentSummary' },
      { text: 'preventingClosure' },
      { text: 'outstandingDocuments' },
      { text: 'outstandingInformation' },
      { text: 'outstandingPayments' },
      { group: 'potentialLiability' },
      { text: 'currentEstimatedLiability' },
      { group: 'legalActionExpected' },
      { header: '15. NEXT ACTION ITEMS' },
      { text: 'nextActions' },
      { header: '16. MANAGEMENT REVIEW' },
      { text: 'lastReviewDate' },
      { text: 'reviewedBy' },
      { group: 'managementStatus' },
      { text: 'managementNotes' },
      { header: '17. SETTLEMENT / RESOLUTION' },
      { group: 'resolution' },
      { text: 'resolutionOther' },
      { text: 'settlementAmount' },
      { text: 'finalPaymentDate' },
      { group: 'releaseObtained' },
      { text: 'releaseDate' },
      { text: 'finalClaimCost' },
      { text: 'insurancePaid' },
      { text: 'companyPaid' },
      { text: 'deductiblePaid' },
      { text: 'totalClaimCost' },
      { group: 'subrogationRecovered' },
      { text: 'subrogationRecovery' },
      { header: '18. CLAIM CLOSURE' },
      { text: 'closureDate' },
      { text: 'closedBy' },
      { text: 'finalClaimStatus' },
      { group: 'docsReceived' },
      { group: 'paymentsCompleted' },
      { group: 'releaseFiled' },
      { group: 'fileComplete' },
      { text: 'lessonsLearned' },
      { text: 'additionalNotes' },
      { text: 'formDate' },
      { group: 'closureRequirements' },
    ],
  },
];

const CLAIMS_CALLBACK_IDS = new Set(CLAIMS_STEPS.map((step) => step.callbackId));

module.exports = {
  GROUPS,
  TEXT_FIELDS,
  TEXT_BY_KEY,
  GROUP_BY_KEY,
  CLAIMS_STEPS,
  CLAIMS_CALLBACK_IDS,
};
